### ISSUE TITLE
Include path of boost headers

### ISSUE THREAD

**Issue by misho104** [GM2Calc/GM2Calc#14]
Hi, I encountered an error in compiling GM2Calc (latest master branch) on my MacOS 14.

```
GM2Calc_src/src/slhaea.h:25:10: fatal error: 'boost/algorithm/string/classification.hpp' file not found
#include <boost/algorithm/string/classification.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
```

I suppose this is because the Boost path is introduced privately in the commit ec6004445424dc1596189e2143b2dd62312c6b2e. In fact, the following patch solves this problem.

```diff
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -40,9 +40,9 @@ target_include_directories(gm2calc
   PUBLIC
     "${PROJECT_SOURCE_DIR}/include"
     "${EIGEN3_INCLUDE_DIR}"
+    "${Boost_INCLUDE_DIRS}"
   PRIVATE
     "${CMAKE_CURRENT_SOURCE_DIR}"
-    "${Boost_INCLUDE_DIRS}"
```

Are there particular reason to load it privately? or otherwise I propose to apply this patch.

Best,
Sho

**Comment by Expander** [comment]
Dear @misho104 

thanks for the report!

The boost headers have been added to the private include paths by intention. This could be done, because the public interface of GM2Calc (to be found in `include/gm2calc/`) is completely independent of boost. By making the boost headers private, the "consurmers" of the GM2Calc library do not need boost. (Boost is only needed for the compilation of GM2Calc.) This can simplify the distribution of GM2Calc significantly, because installing boost is not trivial on all platforms (unfortunately).

Making the boost headers private has been tested with many different setups on Linux, MacOS and Windows with different configurations (using github's actions and various virtual machines from the conan center). For this reason I'm puzzled why you get this error message.

In order to trace the issue, could you please paste the last few lines (that include the error) from the command
~~~
make VERBOSE=1
~~~
? Could you please also give some more details on the operating system you are using? Do you apply patches to GM2Calc locally or similar?

Thanks a lot in advance!

**Comment by misho104** [comment]
It might be because usually `-I` for Eigen3 and Boost are coincide. In my environment they (somehow) locates at
```
/usr/local/include/eigen3/Eigen/Core # (-> -I/u/l/i/eigen3
/usr/local/include/boost/regex.h     # (-> -I/u/l/i
```
but it is fair to keep it private as it is well-tested.

This is a full log, starting from git clone.
```console
$ git clone https://github.com/GM2Calc/GM2Calc.git GM2Calc_src
$ cd GM2Calc
$ cmake ../GM2Calc_src
(snip)
-- Found Boost: /usr/local/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found suitable version "1.78.0", minimum required is "1.37.0")
-- Found Eigen3: /usr/local/include/eigen3 (Required is at least version "3.1")
(snip)

$ make VERBOSE=1
(snip)
[ 43%] Building CXX object src/CMakeFiles/gm2calc.x.dir/gm2calc.cpp.o
cd /Users/misho/HEPcodes/GM2Calc/src && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -I/Users/misho/HEPcodes/GM2Calc/src -I/Users/misho/HEPcodes/GM2Calc_src/include -I/usr/local/include/eigen3 -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.14 -std=gnu++14 -MD -MT src/CMakeFiles/gm2calc.x.dir/gm2calc.cpp.o -MF CMakeFiles/gm2calc.x.dir/gm2calc.cpp.o.d -o CMakeFiles/gm2calc.x.dir/gm2calc.cpp.o -c /Users/misho/HEPcodes/GM2Calc_src/src/gm2calc.cpp
In file included from /Users/misho/HEPcodes/GM2Calc_src/src/gm2calc.cpp:24:
In file included from /Users/misho/HEPcodes/GM2Calc_src/include/gm2calc/MSSMNoFV_onshell.hpp:22:
In file included from /Users/misho/HEPcodes/GM2Calc_src/include/gm2calc/MSSMNoFV_onshell_mass_eigenstates.hpp:32:
In file included from /Users/misho/HEPcodes/GM2Calc_src/include/gm2calc/MSSMNoFV_onshell_soft_parameters.hpp:22:
In file included from /Users/misho/HEPcodes/GM2Calc_src/include/gm2calc/MSSMNoFV_onshell_susy_parameters.hpp:24:
In file included from /usr/local/include/eigen3/Eigen/Core:15:
/usr/local/include/eigen3/Eigen/src/Core/util/DisableStupidWarnings.h:48:38: warning: unknown warning group '-Wimplicit-int-float-conversion', ignored [-Wunknown-warning-option]
    #pragma clang diagnostic ignored "-Wimplicit-int-float-conversion"
                                     ^
In file included from /Users/misho/HEPcodes/GM2Calc_src/src/gm2calc.cpp:32:
In file included from /Users/misho/HEPcodes/GM2Calc_src/src/gm2_slha_io.hpp:24:
/Users/misho/HEPcodes/GM2Calc_src/src/slhaea.h:25:10: fatal error: 'boost/algorithm/string/classification.hpp' file not found
#include <boost/algorithm/string/classification.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
make[2]: *** [src/CMakeFiles/gm2calc.x.dir/gm2calc.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/gm2calc.x.dir/all] Error 2
make: *** [all] Error 2
```

Best,
Sho

**Comment by Expander** [comment]
Many thanks for the log! On my machine I get:
~~~.bash
[ 47%] Building CXX object src/CMakeFiles/gm2calc.x.dir/gm2calc.cpp.o
cd /home/avoigt/research/GM2Calc-master/build/src && /usr/bin/c++  -I/home/avoigt/research/GM2Calc-master/build/src -I/home/avoigt/research/GM2Calc-master/include -I/usr/include/eigen3 -O3 -DNDEBUG -std=gnu++14 -o CMakeFiles/gm2calc.x.dir/gm2calc.cpp.o -c /home/avoigt/research/GM2Calc-master/src/gm2calc.cpp
~~~
So, on my machine the boost headers are not included either when building `gm2calc.cpp.o`, which is strange. However, I don't get a compiler error.

So, you may be right, this may be due to a coincidence of the location of the headers. My g++ includes by default `/usr/include`. On my machine the boost and Eigen headers are located in sub-directories of this one.

So, I have the feeling you've spotted a bug here. Maybe the patch should be:
~~~.patch
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 1bc7e72..4e0d373 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -56,7 +56,7 @@ install(
 # GM2Calc main executable
 add_executable(gm2calc.x gm2calc.cpp)
 target_link_libraries(gm2calc.x PRIVATE GM2Calc::GM2Calc)
-target_include_directories(gm2calc.x PRIVATE ${CMAKE_CURRENT_BINARY_DIR})
+target_include_directories(gm2calc.x PRIVATE "${CMAKE_CURRENT_BINARY_DIR}" "${Boost_INCLUDE_DIRS}")
 
 install(
   TARGETS gm2calc.x
~~~

**Comment by Expander** [comment]
Would you mind trying the patch in the `fix-boost-include-dir` branch to see if this fixes the compilation error that you see?

**Comment by misho104** [comment]
confirmed that this patch solves my issue.

> Maybe the patch should be:

**Comment by Expander** [comment]
Great, thanks a lot!
